baseURL = "https://blog.karashi.org/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "poppen's blog"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""
theme = "cactus-plus"

hasCJKLanguage = true
preserveTaxonomyNames = true
enableRobotsTXT = true # generate robots.txt

[params]
	dateformat = "2006/01/02"

	author = "poppen"
	description = "poppen's blog"
	#big = ""

	twitter = "poppen"
	# facebook = "your_facebook_id"

	enableRSS = true
	enableToc = true

	enableDisqus = true
	disqusShortname = "poppens-blog"

	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false

	enableGoogleAnalytics = false

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = ["/css/custom.css"]
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
iconFont = "font-awesome"
# The social icons can be styled differently if you use mono as font - circle, rounded, or empty
socialIconStyle = ""

# Add additional social link entries underneath
[social]
	twitter-square = "https://www.twitter.com/poppen"
	github-square = "https://www.github.com/poppen"
	steam-square = "https://steamcommunity.com/id/poppen_jp"
